server:
  servlet:
    context-path: /
  port: 8080

spring:
  cache:
    type: caffeine
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 2
        max-wait: 5000ms
        min-idle: 0
        max-idle: 2

logging:
  level:
    co.tunan.tucache: debug
  file:
    name: logs/log.log

tucache:
  profiles:
    cache-prefix: "tu_key_test:"
    pool:
      core-pool-size: 2